const USER_AGENT =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36,gzip(gfe)';

const INNERTUBE_API_URL = 'https://www.youtube.com/youtubei/v1/player?prettyPrint=false';
const INNERTUBE_CLIENT_VERSION = '20.10.38';
const INNERTUBE_CONTEXT = {
  client: {
    clientName: 'ANDROID',
    clientVersion: INNERTUBE_CLIENT_VERSION,
  },
};
const INNERTUBE_USER_AGENT = `com.google.android.youtube/${INNERTUBE_CLIENT_VERSION} (Linux; U; Android 14)`;

export interface YouTubeCaptionsResult {
  language: string;
  languageName?: string;
  isAutoGenerated: boolean;
  lines: { time: number; text: string }[];
}

function decodeEntities(text: string): string {
  return text
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/&#x([0-9a-fA-F]+);/g, (_, hex) => String.fromCodePoint(parseInt(hex, 16)))
    .replace(/&#(\d+);/g, (_, dec) => String.fromCodePoint(parseInt(dec, 10)));
}

function parseTranscriptXml(xml: string): { time: number; text: string }[] {
  const results: { time: number; text: string }[] = [];

  // Format 1: srv3 format (<p t="ms" d="ms">...)
  const pRegex = /<p\s+t="(\d+)"\s+d="(\d+)"[^>]*>([\s\S]*?)<\/p>/g;
  let match;
  while ((match = pRegex.exec(xml)) !== null) {
    const startMs = parseInt(match[1], 10);
    const inner = match[3];
    let text = '';
    const sRegex = /<s[^>]*>([^<]*)<\/s>/g;
    let sMatch;
    while ((sMatch = sRegex.exec(inner)) !== null) {
      text += sMatch[1];
    }
    if (!text) text = inner.replace(/<[^>]+>/g, '');
    text = decodeEntities(text).replace(/\s+/g, ' ').trim();
    if (text) {
      const timeInSec = Math.round((startMs / 1000) * 100) / 100;
      results.push({ time: timeInSec, text });
    }
  }

  if (results.length > 0) {
    return results.sort((a, b) => a.time - b.time);
  }

  // Format 2: classic format (<text start="sec" dur="sec">...)
  const classicRegex = /<text\s+start="([^"]*)"\s+dur="([^"]*)"[^>]*>([\s\S]*?)<\/text>/g;
  while ((match = classicRegex.exec(xml)) !== null) {
    const timeInSec = Math.round(parseFloat(match[1]) * 100) / 100;
    const text = decodeEntities(match[3]).replace(/<[^>]+>/g, '').replace(/\s+/g, ' ').trim();
    if (text) {
      results.push({ time: timeInSec, text });
    }
  }

  return results.sort((a, b) => a.time - b.time);
}

/**
 * Fetches and parses timed subtitles/captions directly from a YouTube video ID.
 * Supports creator uploaded captions and auto-generated captions in Thai and other languages.
 */
export async function fetchYouTubeSubtitles(videoId: string): Promise<YouTubeCaptionsResult | null> {
  const cleanId = videoId.trim();
  if (!cleanId || cleanId.length !== 11) return null;

  let captionTracks: any[] = [];

  // Strategy 1: Android InnerTube Player API
  try {
    const resp = await fetch(INNERTUBE_API_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'User-Agent': INNERTUBE_USER_AGENT,
      },
      body: JSON.stringify({
        context: INNERTUBE_CONTEXT,
        videoId: cleanId,
      }),
    });
    if (resp.ok) {
      const data = (await resp.json()) as any;
      captionTracks = data?.captions?.playerCaptionsTracklistRenderer?.captionTracks || [];
    }
  } catch (err) {
    // Failover to HTML scraping
  }

  // Strategy 2: Web page HTML scraping fallback
  if (!captionTracks.length) {
    try {
      const pageResp = await fetch(`https://www.youtube.com/watch?v=${cleanId}`, {
        headers: {
          'User-Agent': USER_AGENT,
          'Accept-Language': 'th,en-US;q=0.9,en;q=0.8',
        },
      });
      if (pageResp.ok) {
        const html = await pageResp.text();
        const match = html.match(/ytInitialPlayerResponse\s*=\s*({.+?});/);
        if (match) {
          const data = JSON.parse(match[1]);
          captionTracks = data?.captions?.playerCaptionsTracklistRenderer?.captionTracks || [];
        }
      }
    } catch (err) {
      // Ignore
    }
  }

  if (!captionTracks || captionTracks.length === 0) {
    return null;
  }

  // Language Selection Preference:
  // 1. Thai Manual Subtitle
  // 2. Thai Auto Subtitle
  // 3. English Manual Subtitle
  // 4. English Auto Subtitle
  // 5. First available caption track
  const preferredTrack =
    captionTracks.find((t) => t.languageCode === 'th' && !t.kind) ||
    captionTracks.find((t) => t.languageCode === 'th') ||
    captionTracks.find((t) => t.languageCode.startsWith('en') && !t.kind) ||
    captionTracks.find((t) => t.languageCode.startsWith('en')) ||
    captionTracks.find((t) => !t.kind) ||
    captionTracks[0];

  if (!preferredTrack || !preferredTrack.baseUrl) {
    return null;
  }

  try {
    const subResp = await fetch(preferredTrack.baseUrl, {
      headers: {
        'User-Agent': USER_AGENT,
        Referer: `https://www.youtube.com/watch?v=${cleanId}`,
      },
    });

    if (!subResp.ok) return null;
    const xml = await subResp.text();
    const lines = parseTranscriptXml(xml);

    if (lines.length === 0) return null;

    return {
      language: preferredTrack.languageCode || 'unknown',
      languageName: preferredTrack.name?.simpleText || preferredTrack.languageCode,
      isAutoGenerated: preferredTrack.kind === 'asr',
      lines,
    };
  } catch (err) {
    console.error('Failed to parse subtitle XML for video', cleanId, err);
    return null;
  }
}
